/* TRANSACTIONS */
export const GET_TRANSACTIONS = "GET_TRANSACTIONS"
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS"
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL"
export const GET_TRANSACTION_DETAIL = "GET_TRANSACTION_DETAIL"
export const GET_TRANSACTION_DETAIL_SUCCESS = "GET_TRANSACTION_DETAIL_SUCCESS"
export const GET_TRANSACTION_DETAIL_FAIL = "GET_TRANSACTION_DETAIL_FAIL"
